# Generated by Django 4.0.5 on 2022-07-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventportal', '0002_note_note_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fest_name', models.CharField(max_length=255)),
                ('fest_venue', models.CharField(max_length=255)),
                ('fest_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
